CREATE TABLE DEPL(DEPT_ID NUMBER,DEPT_NAME VARCHAR(50),LOCATION VARCHAR2(50));
CREATE TABLE EMPLS(EMP_ID NUMBER,EMP_NAME VARCHAR(50),SALARY VARCHAR2(50),DEPT_ID NUMBER);

INSERT INTO EMPLS VALUES(101,'RAJ',40000,80);
INSERT INTO EMPLS VALUES(102,'NEHA',55000,20);
INSERT INTO EMPLS VALUES(103,'AMIT',65000,20);
INSERT INTO EMPLS VALUES(104,'PRIYANKA',75000,30);
INSERT INTO EMPLS VALUES(105,'KIRAN',35000,10);

INSERT INTO DEPL VALUES(801,'HR','DELHI');
INSERT INTO DEPL VALUES(10,'IT','KOLKATA');
INSERT INTO DEPL VALUES(20,A'FINANCE','CHENNAI');
INSERT INTO DEPL VALUES(80,'DS','MUMBAI');

SELECT E.EMP_NAME,D.DEPT_NAME FROM EMPLS E, DEPL D WHERE E.DEPT_ID=D.DEPT_ID;


-------------
CREATE TABLE SALARY_GRADE(GRADE VARCHAR(50),MIN_SALARY NUMBER,MAX_SALARY NUMBER);
INSERT INTO SALARY_GRADE VALUES('C',40001,60000);

SELECT E.EMP_NAME,E.SALARY ,S.GRADE FROM EMPLS E, SALARY_GRADE S WHERE E.SALARY BETWEEN S.MIN_SALARY AND S.MAX_SALARY;

---------------------

CREATE TABLE employee (emp_id NUMBER PRIMARY KEY,emp_name VARCHAR2(50),designation VARCHAR2(50),salary NUMBER,manager_id NUMBER);

-- INSERT DATA
INSERT INTO employee VALUES (1, 'Raj', 'CEO', 90000, NULL);
INSERT INTO employee VALUES (2, 'Aman', 'Manager', 70000, 1);
INSERT INTO employee VALUES (3, 'Priya', 'Manager', 68000, 1);
INSERT INTO employee VALUES (4, 'Neha', 'Developer', 50000, 2);
INSERT INTO employee VALUES (5, 'Karan', 'Tester', 45000, 2);
INSERT INTO employee VALUES (6, 'Simran', 'HR', 40000, 3);
INSERT INTO employee VALUES (7, 'Rohit', 'Developer', 52000, 3);

SELECT e.emp_name AS "Employee Name",m.emp_name AS "Manager Name" FROM employee e LEFT JOIN employee m ON e.manager_id = m.emp_id;

SELECT e.emp_name AS "Employee Name", e.designation AS "Employee Designation", m.emp_name AS "Manager Name" FROM employee e LEFT JOIN  employee m ON e.manager_id = m.emp_id;

SELECT e.emp_name AS "Employee Name", m.emp_name AS "Manager Name" FROM employee e LEFT OUTER JOIN employee m ON e.manager_id = m.emp_id;




