-- TASK 1: Display Employee Details
--DECLARE
--v_name EMM.EMP_NAME%TYPE;
--v_sal EMM.SALARY%TYPE;
--BEGIN
--SELECT EMP_NAME, SALARY INTO v_name, v_sal FROM EMM WHERE EMP_ID = 101;
--END;
--/

-- TASK 2: Check Salary Category
DECLARE
v_sal EMM.SALARY%TYPE;
BEGIN
SELECT SALARY INTO v_sal FROM EMM WHERE EMP_ID = 101;
IF v_sal > 50000 THEN
NULL;
ELSE
NULL;
END IF;
END;
/

-- TASK 3: Update Bonus Using IF Condition
DECLARE
v_sal EMM.SALARY%TYPE;
BEGIN
SELECT SALARY INTO v_sal FROM EMM WHERE EMP_ID = 101;
IF v_sal > 40000 THEN
UPDATE EMM SET BONUS = 5000 WHERE EMP_ID = 101;
ELSE
UPDATE EMM SET BONUS = 2000 WHERE EMP_ID = 101;
END IF;
COMMIT;
END;
/

-- TASK 4: Insert Multiple Employees Using LOOP
DECLARE
v_id NUMBER := 201;
BEGIN
LOOP
INSERT INTO EMM (EMP_ID, EMP_NAME, SALARY, DEPT_ID, BONUS, STATUS, HIRE_DATE)
VALUES (v_id, 'Employee'||v_id, 30000, 10, 1000, 'ACTIVE', SYSDATE);
v_id := v_id + 1;
EXIT WHEN v_id > 205;
END LOOP;
COMMIT;
END;
/

-- TASK 5: Print Numbers Using WHILE LOOP
DECLARE
v_num NUMBER := 1;
BEGIN
WHILE v_num <= 10 LOOP
v_num := v_num + 1;
END LOOP;
END;
/

-- TASK 6: Increase Salary Using FOR LOOP
BEGIN
FOR v_id IN 101..105 LOOP
UPDATE EMM
SET SALARY = SALARY + (SALARY * 0.05)
WHERE EMP_ID = v_id;
END LOOP;
COMMIT;
END;
/

-- TASK 7: Department Wise Message
DECLARE
v_dept EMM.DEPT_ID%TYPE;
BEGIN
SELECT DEPT_ID INTO v_dept FROM EMM WHERE EMP_ID = 101;
CASE v_dept
WHEN 10 THEN NULL;
WHEN 20 THEN NULL;
WHEN 30 THEN NULL;
ELSE NULL;
END CASE;
END;
/

-- TASK 8: Delete Employees Using FOR LOOP
BEGIN
FOR v_id IN 201..205 LOOP
DELETE FROM EMM WHERE EMP_ID = v_id;
END LOOP;
COMMIT;
END;
/

-- TASK 9: Find Highest Salary
DECLARE
v_max_sal NUMBER;
BEGIN
SELECT MAX(SALARY) INTO v_max_sal FROM EMM;
END;
/

-- TASK 10: Nested IF Condition
DECLARE
v_sal EMM.SALARY%TYPE;
v_bonus EMM.BONUS%TYPE;
BEGIN
SELECT SALARY, BONUS INTO v_sal, v_bonus FROM EMM WHERE EMP_ID = 101;
IF v_sal > 50000 THEN
IF v_bonus > 5000 THEN
NULL;
ELSE
NULL;
END IF;
ELSE
NULL;
END IF;
END;
/

-- TASK 11: Count Employees Department Wise
DECLARE
v_count NUMBER;
BEGIN
SELECT COUNT(*) INTO v_count FROM EMM WHERE DEPT_ID = 10;
END;
/
