DECLARE
    NAME VARCHAR2(20);
    SALARY NUMBER;

BEGIN
NAME:='HII';
SALARY:=1000;
DBMS_OUTPUT.PUT_LINE(SALARY);
   
END;
/


BEGIN
    INSERT INTO EMM
    VALUES(1,'JP',55000,1,'MYS','IT',2000,60000,2200);
    COMMIT;
END;
/
    
DECLARE
    SALARY NUMBER:=50000;
BEGIN
IF SALARY>40000 THEN
    DBMS_OUTPUT.PUT_LINE(SALARY);
END IF;
END;
/

DECLARE
    MARKS NUMBER:=50;
BEGIN
IF MARKS>=55 THEN
    DBMS_OUTPUT.PUT_LINE('PASS');
ELSE
     DBMS_OUTPUT.PUT_LINE('FAIL');
    
END IF;
END;
/

DECLARE
    MARKS NUMBER:=75;
BEGIN
IF MARKS>=90 THEN
    DBMS_OUTPUT.PUT_LINE('GRADE A');
ELSIF MARKS>=60 THEN
     DBMS_OUTPUT.PUT_LINE('GRADE B');
ELSE
    DBMS_OUTPUT.PUT_LINE('GRADE C');
    
END IF;
END;
/


DECLARE
    DAY NUMBER:=1;
BEGIN
    CASE
    WHEN DAY=1 THEN
    DBMS_OUTPUT.PUT_LINE('MONDAY');
WHEN DAY=2 THEN
     DBMS_OUTPUT.PUT_LINE('TUESDAY');
ELSE
    DBMS_OUTPUT.PUT_LINE('INAVILD');
    
END CASE;
END;
/

DECLARE
    NUM NUMBER:=1;
BEGIN
    LOOP
    DBMS_OUTPUT.PUT_LINE(NUM);
    NUM:=NUM+1;
    EXIT WHEN NUM>5;
    
END LOOP;
END;
/

DECLARE
    NUM NUMBER:=1;
    
BEGIN
    WHILE NUM<=5 LOOP
    DBMS_OUTPUT.PUT_LINE(NUM);
    NUM:=NUM+1;
   
    
END LOOP;
END;
/


    
BEGIN
    FOR I IN  1..5 LOOP
    DBMS_OUTPUT.PUT_LINE(I);
    
END LOOP;
END;
/


    
BEGIN
    FOR I IN (SELECT EMP_ID FROM EMM)
    LOOP
    UPDATE EMM
    SET BONUS=80000
    WHERE EMP_ID=I.EMP_ID;
    END LOOP;
COMMIT;
END;
/

    
BEGIN
    FOR I IN 1..5
    LOOP
    CONTINUE WHEN I>3;
    DBMS_OUTPUT.PUT_LINE(I);
    END LOOP;
END;
/


-------------------------


-- TASK 1: Display Employee Details
DECLARE
v_name EMM.EMP_NAME%TYPE;
v_sal EMM.SALARY%TYPE;
BEGIN
SELECT EMP_NAME, SALARY INTO v_name, v_sal FROM EMM WHERE EMP_ID = 101;
END;
/

-- TASK 2: Check Salary Category
DECLARE
v_sal EMM.SALARY%TYPE;
BEGIN
SELECT SALARY INTO v_sal FROM EMM WHERE EMP_ID = 101;
IF v_sal > 50000 THEN
NULL;
ELSE
NULL;
END IF;
END;
/

-- TASK 3: Update Bonus Using IF Condition
DECLARE
v_sal EMM.SALARY%TYPE;
BEGIN
SELECT SALARY INTO v_sal FROM EMM WHERE EMP_ID = 101;
IF v_sal > 40000 THEN
UPDATE EMM SET BONUS = 5000 WHERE EMP_ID = 101;
ELSE
UPDATE EMM SET BONUS = 2000 WHERE EMP_ID = 101;
END IF;
COMMIT;
END;
/

-- TASK 4: Insert Multiple Employees Using LOOP
DECLARE
v_id NUMBER := 201;
BEGIN
LOOP
INSERT INTO EMM (EMP_ID, EMP_NAME, SALARY, DEPT_ID, BONUS, STATUS, HIRE_DATE)
VALUES (v_id, 'Employee'||v_id, 30000, 10, 1000, 'ACTIVE', SYSDATE);
v_id := v_id + 1;
EXIT WHEN v_id > 205;
END LOOP;
COMMIT;
END;
/

-- TASK 5: Print Numbers Using WHILE LOOP
DECLARE
v_num NUMBER := 1;
BEGIN
WHILE v_num <= 10 LOOP
v_num := v_num + 1;
END LOOP;
END;
/

-- TASK 6: Increase Salary Using FOR LOOP
BEGIN
FOR v_id IN 101..105 LOOP
UPDATE EMM
SET SALARY = SALARY + (SALARY * 0.05)
WHERE EMP_ID = v_id;
END LOOP;
COMMIT;
END;
/

-- TASK 7: Department Wise Message
DECLARE
v_dept EMM.DEPT_ID%TYPE;
BEGIN
SELECT DEPT_ID INTO v_dept FROM EMM WHERE EMP_ID = 101;
CASE v_dept
WHEN 10 THEN NULL;
WHEN 20 THEN NULL;
WHEN 30 THEN NULL;
ELSE NULL;
END CASE;
END;
/

-- TASK 8: Delete Employees Using FOR LOOP
BEGIN
FOR v_id IN 201..205 LOOP
DELETE FROM EMM WHERE EMP_ID = v_id;
END LOOP;
COMMIT;
END;
/

-- TASK 9: Find Highest Salary
DECLARE
v_max_sal NUMBER;
BEGIN
SELECT MAX(SALARY) INTO v_max_sal FROM EMM;
END;
/

-- TASK 10: Nested IF Condition
DECLARE
v_sal EMM.SALARY%TYPE;
v_bonus EMM.BONUS%TYPE;
BEGIN
SELECT SALARY, BONUS INTO v_sal, v_bonus FROM EMM WHERE EMP_ID = 101;
IF v_sal > 50000 THEN
IF v_bonus > 5000 THEN
NULL;
ELSE
NULL;
END IF;
ELSE
NULL;
END IF;
END;
/


---------------------------------
CREATE TABLE BANK(AC_NO NUMBER PRIMARY KEY,CNAME VARCHAR2(30),ACTYPE VARCHAR2(30),BALANCE NUMBER);
INSERT INTO BANK VALUES(1001,'RAHUL','SAVINGS',50000);
INSERT INTO BANK VALUES(1002,'AMUL','CURRENT',20000);
INSERT INTO BANK VALUES(1003,'ROHAN','SAVINGS',15000);

CREATE TABLE HISTORY(TID NUMBER PRIMARY KEY, ACNO NUMBER, CNAME VARCHAR2(30), TYPE VARCHAR(30), OLDBALANCE NUMBER,AMOUNT NUMBER,NEWBALANCE NUMBER,TDATE DATE);

DECLARE
     ACNUMBER NUMBER;
     CNAME VARCHAR2(30);
     ACTYPE VARCHAR2(30);

     BALANCE NUMBER;
     OLDBALANCE NUMBER;
     NEWBALANCE NUMBER;
     AMOUNT NUMBER:=3000;
     MINBALANCE NUMBER;
     TTYPE VARCHAR2(20)
         :='WITHDRAW';
  BEGIN
      SELECT AC_NO,CNAME,ACTYPE,BALANCE INTO ACNUMBER,CNAME,ACTYPE,BALANCE FROM BANK WHERE AC_NO=1001;
DBMS_OUTPUT.PUT_LINE(CNAME);
DBMS_OUTPUT.PUT_LINE(BALANCE);
    --WHILE COUNTER<=1003
    --LOOP
    --SELECT ACNO,CNAME,ACTYPE,BALANCE INTO CNAME,ACTYPE,BALANCE FROM BANK WHERE ACNO=COUNTER;
    
    NULL;
END;
/



--------------------