CREATE TABLE STUDENT (STUDENT_ID NUMBER,NAME VARCHAR2(30), CITY VARCHAR2(20), COURSE VARCHAR2(20),MARKS NUMBER,ADMISSION_DATE DATE);

CREATE TABLE EMPLOYEE (EMP_ID NUMBER,EMP_NAME VARCHAR2(30),DEPARTMENT VARCHAR2(20),SALARY NUMBER,HIRE_DATE DATE,BONUS NUMBER);

CREATE TABLE PRODUCT (PRODUCT_ID NUMBER,PRODUCT_NAME VARCHAR2(30),CATEGORY VARCHAR2(20),PRICE NUMBER,STOCK NUMBER);



INSERT INTO STUDENT VALUES (101, 'Aman', 'Bhopal', 'BCA', 78, TO_DATE('12-06-2023', 'DD-MM-YYYY'));
INSERT INTO STUDENT VALUES (102, 'Riya', 'Indore', 'MCA', 88, TO_DATE('15-07-2023', 'DD-MM-YYYY'));
INSERT INTO STUDENT VALUES (103, 'Kunal', 'Delhi', 'BBA', 67, TO_DATE('11-01-2022', 'DD-MM-YYYY'));
INSERT INTO STUDENT VALUES (104, 'Neha', 'Mumbai', 'BCA', 91, TO_DATE('25-09-2023', 'DD-MM-YYYY'));
INSERT INTO STUDENT VALUES (105, 'Arjun', 'Pune', 'MBA', 55, TO_DATE('10-03-2021', 'DD-MM-YYYY'));

INSERT INTO EMPLOYEE VALUES (1, 'Rahul', 'HR', 25000, TO_DATE('11-01-2020', 'DD-MM-YYYY'), 2000);
INSERT INTO EMPLOYEE VALUES (2, 'Sneha', 'IT', 45000, TO_DATE('15-02-2019', 'DD-MM-YYYY'), 5000);
INSERT INTO EMPLOYEE VALUES (3, 'Vikas', 'SALES', 30000, TO_DATE('10-03-2021', 'DD-MM-YYYY'), 3000);
INSERT INTO EMPLOYEE VALUES (4, 'Pooja', 'IT', 55000, TO_DATE('18-07-2018', 'DD-MM-YYYY'), 7000);
INSERT INTO EMPLOYEE VALUES (5, 'Amit', 'HR', 28000, TO_DATE('22-08-2022', 'DD-MM-YYYY'), 7000);

INSERT INTO PRODUCT VALUES (201, 'Laptop', 'Electronics', 55000, 10);
INSERT INTO PRODUCT VALUES (202, 'Mouse', 'Electronics', 700, 50);
INSERT INTO PRODUCT VALUES (203, 'Chair', 'Furniture', 3500, 20);
INSERT INTO PRODUCT VALUES (204, 'Table', 'Furniture', 4500, 15);
INSERT INTO PRODUCT VALUES (205, 'Mobile', 'Electronics', 25000, 25);


SELECT * FROM STUDENT;


SELECT NAME, MARKS FROM STUDENT;

SELECT * FROM EMPLOYEE;


SELECT PRODUCT_NAME, PRICE FROM PRODUCT;

SELECT DISTINCT COURSE FROM STUDENT;


SELECT * FROM STUDENT WHERE CITY = 'Bhopal';

SELECT * FROM EMPLOYEE WHERE DEPARTMENT = 'IT';

SELECT * FROM PRODUCT WHERE PRICE > 5000;

SELECT * FROM STUDENT WHERE MARKS > 70;

SELECT * FROM EMPLOYEE WHERE SALARY < 40000;


SELECT * FROM STUDENT WHERE MARKS BETWEEN 60 AND 90;


SELECT * FROM EMPLOYEE WHERE SALARY BETWEEN 25000 AND 50000;


SELECT * FROM PRODUCT WHERE CATEGORY = 'Electronics';

SELECT * FROM STUDENT WHERE NAME LIKE 'A%';

SELECT * FROM EMPLOYEE WHERE EMP_NAME LIKE '%a';

SELECT * FROM STUDENT WHERE CITY LIKE '%o%';

SELECT * FROM EMPLOYEE WHERE BONUS IS NULL;


SELECT * FROM PRODUCT WHERE STOCK NOT BETWEEN 10 AND 30;

SELECT * FROM STUDENT WHERE COURSE IN ('BCA', 'MCA');


SELECT * FROM EMPLOYEE WHERE DEPARTMENT != 'IT';


SELECT * FROM STUDENT ORDER BY MARKS ASC;


SELECT * FROM EMPLOYEE ORDER BY SALARY DESC;


SELECT * FROM PRODUCT ORDER BY PRICE;

SELECT NAME FROM STUDENT ORDER BY NAME;


SELECT * FROM EMPLOYEE ORDER BY DEPARTMENT, SALARY;


SELECT EMP_NAME, SALARY, SQRT(SALARY) AS SQRT_SALARY FROM EMPLOYEE;

SELECT MAX(SALARY) AS MAX_SALARY,MIN(SALARY) AS MIN_SALARY,AVG(SALARY) AS AVG_SALARYFROM EMPLOYEE;

SELECT EMP_NAME, SALARY, ROUND(SALARY * 1.1) AS INCREASED_SALARY, POWER(SALARY, 2) AS SALARY_SQUARE,MOD(SALARY, 5000) AS REMAINDERFROM EMPLOYEE;