DECLARE
     ACNUMBER NUMBER;
     CNAME VARCHAR2(30);
     ACTYPE VARCHAR2(30);

     BALANCE NUMBER;
     OLDBALANCE NUMBER;
     NEWBALANCE NUMBER;
     AMOUNT NUMBER:=3000;
     MINBALANCE NUMBER;
     TTYPE VARCHAR2(20)
         :='SAVINGS';
MIN_BALANCE NUMBER;
---BALANCE NUMBER;

  BEGIN
   IF TTYPE='SAVINGS' THEN MINBALANCE:=50000;
   ELSE
       MINBALANCE:=10000
   END IF;
   DBMS_OUTPUT.PUT_LINE(MINBALANCE);
    --WHILE COUNTER<=1003
    --LOOP
    --SELECT ACNO,CNAME,ACTYPE,BALANCE INTO CNAME,ACTYPE,BALANCE FROM BANK WHERE ACNO=COUNTER;
    
   -- NULL;
END;
/