REATE TABLE DEPART(DEPT_ID NUMBER,DEPT_NAME VARCHAR(50));
CREATE TABLE EMPS(EMP_ID NUMBER,EMP_NAME VARCHAR(50),JOB VARCHAR(50),SALARY NUMBER,DEPT_ID NUMBER,MANAGER_ID NUMBER);

INSERT INTO DEPART VALUES(10,'HR');
INSERT INTO DEPART VALUES(20,'HR');
INSERT INTO DEPART VALUES(30,'FINANCE');
INSERT INTO DEPART VALUES(40,'SALES');

INSERT INTO EMPS VALUES(1,'RAJ','MANAGER',70000,10,NULL);

INSERT INTO EMPS VALUES(2,'AMIT','CLERK',40000,10,1);

SELECT  EMP_NAME, SALARY FROM EMPS;

SELECT  EMP_NAME, SALARY FROM EMPS;

SELECT * FROM EMPS WHERE SALARY >40000;

SELECT * FROM EMPS WHERE SALARY BETWEEN 30000 AND 60000;

SELECT * FROM EMPS WHERE EMP_NAME LIKE 'R%';

SELECT * FROM EMPS WHERE JOB IN ('CLERK','ANALYST');

SELECT * FROM EMPS ORDER BY SALARY DESC;

SELECT * FROM EMPS ORDER BY EMP_NAME ASC;

SELECT EMP_NAME,SALARY,SALARY*12 AS ANNUAL_SALARY FROM EMPS;

SELECT EMP_NAME,SALARY,SALARY+(SALARY*0.10) AS INCREASED_SALARY FROM_EMPLOYEES;

SELECT DEPART_ID, COUNT(*) AS TOTAL_EMPLOYEES FROM EMPS  GROUP BY DEPART_ID;

SELECT DEPART_ID, AVG(SALARY) AS AVERAGE_SALARY FROM EMPS GROUP BY DEPART_ID;

SELECT DEPART_ID, MIN(SALARY) AS LOWEST_SALARY FROM EMPS GROUP BY DEPART_ID;

SELECT DEPART_ID, COUNT(*) AS TOTAL_EMPLOYEES FROM EMPS GROUP BY DEPART_ID HAVING COUNT(*)>2;

SELECT E.EMP_NAME, E.JOB D.DEPT-NAME FROM EMPS E JOIN DEPART D ON E.DEPART_ID=D.DEPART_ID;
