-- SET SERVEROUTPUT ON;
-- DECLARE
--     V_DEPT N_TT.DEPT%TYPE := &DEPT;
--     V_NAME N_TT.NAME%TYPE;
-- BEGIN
--     SELECT NAME
--     INTO V_NAME
--     FROM N_TT
--     WHERE DEPT= V_DEPT;
--     DBMS_OUTPUT.PUT_LINE('NAME : ' || V_NAME);

-- EXCEPTION 
--     WHEN NO_DATA_FOUND THEN
--         DBMS_OUTPUT.PUT_LINE('NOT FOUND');
--     COMMIT;
-- END;
-- /


-- SET SERVEROUTPUT ON;
-- BEGIN
--     UPDATE N_TT
--     SET SALARY=SALARY+1000
--     WHERE DEPT=101;
--     IF SQL%FOUND THEN
--         DBMS_OUTPUT.PUT_LINE(SQL%ROWCOUNT || 'ROW UPDATED');
--     ELSE
--         DBMS_OUTPUT.PUT_LINE('NO ROW UPDATED');
--     COMMIT;

--     END IF;
-- END;
-- /




-- SET SERVEROUTPUT ON;
-- BEGIN
--     DELETE FROM N_TT
    
--     WHERE DEPT=101;
--     IF SQL%FOUND THEN
--         DBMS_OUTPUT.PUT_LINE('DEPT NOT FOUND');
--     ELSE
--         DBMS_OUTPUT.PUT_LINE('ROW DELETED');
--     COMMIT;

--     END IF;
-- END;
-- /

-- SET SERVEROUTPUT ON;
-- DECLARE
--     CURSOR C1 IS SELECT NAME,DEPT FROM N_TT;
--     NAMESS N_TT.NAME%TYPE;
--     DNO N_TT.DEPT%TYPE;

-- BEGIN
--     OPEN C1;
--         FETCH C1 INTO NAMESS,DNO;
--         IF C1%FOUND THEN
--         DBMS_OUTPUT.PUT_LINE('FETCH SUCCESFUL');
--         DBMS_OUTPUT.PUT_LINE(NAMESS||DNO);
--         END IF;
--         CLOSE C1;
-- END;
-- /

-- SET SERVEROUTPUT ON;
-- DECLARE
-- CURSOR C1 IS SELECT NAME,DEPT,SALARY FROM N_TT;
--     V_NAME N_TT.NAME%TYPE;
--     V_SALARY N_TT.SALARY%TYPE;
--     V_DEPT N_TT.DEPT%TYPE;

-- BEGIN
--     OPEN C1;
--     LOOP
--         FETCH C1 INTO V_NAME,V_DEPT,V_SALARY;
--         EXIT WHEN C1%NOTFOUND
--         DBMS_OUTPUT.PUT_LINE('ROW: ' || C1%ROWCOUNT);
--         DBMS_OUTPUT.PUT_LINE(V_NAME || ' '||V_SALARY||' '||V_DEPT);
--         END LOOP;
--     CLOSE C1;
-- IF NOT C1%ISOPEN THEN DBMS_OUTPUT.PUT_LINE('CURSOR CLOSED');
-- END IF;
-- END;
-- /

-- SELECT * FROM EMPK;

-- INSERT INTO EMPK VALUES(101,'FR',20000,10);

-- INSERT INTO EMPK VALUES(102,'SR',30000,10);

-- INSERT INTO EMPK VALUES(103,'DR',40000,10);

-- INSERT INTO EMPK VALUES(104,'GR',50000,10);

---DELETE FROM EMPK WHERE EMPNO=104;


-- SET SERVEROUTPUT ON;
-- DECLARE
-- CURSOR C1(P_DEPT NUMBER)IS SELECT EMPNO,ENAME,SALARY FROM EMPK
-- WHERE DEPT=P_DEPT;
-- BEGIN
--     DBMS_OUTPUT.PUT_LINE('DEPARTMENT 10');
--     FOR I IN C1(10)
--     LOOP
--   DBMS_OUTPUT.PUT_LINE(I.EMPNO||I.ENAME||I.SALARY);
-- END LOOP;
-- END;
-- /


-- SET SERVEROUTPUT ON;
-- DECLARE
-- CURSOR C1(P_DEPT NUMBER,P_SALARY NUMBER)IS SELECT EMPNO,ENAME,SALARY FROM EMPK
-- WHERE DEPT=P_DEPT AND SALARY >=P_SALARY;
-- BEGIN
--     FOR I IN C1(10,40000)
--     LOOP
--   DBMS_OUTPUT.PUT_LINE(I.ENAME||I.SALARY);
-- END LOOP;
-- END;
-- /



-- SET SERVEROUTPUT ON;
-- DECLARE
-- CURSOR C1(P_DEPT NUMBER)IS SELECT EMPNO,ENAME,SALARY FROM EMPK
-- WHERE DEPT=P_DEPT;
-- V_EMPNO EMPK.EMPNO%TYPE;
-- V_NAME EMPK.EMPNAME%TYPE;
-- BEGIN
--     OPEN C1(10);
--     LOOP
--         FETCH C1 INTO V_EMPNO,V_NAME;
--         EXIT WHEN  C1%NOTFOUND;
--         DBMS_OUTPUT.PUT_LINE(V_EMPNO ||V_NAME);
--     END LOOP;
--   CLOSE C1;
-- END;
-- /

SET SERVEROUTPUT ON;
DECLARE
CURSOR C1(P_DEPTNO NUMBER)IS SELECT EMPNO,SALARY FROM EMPK
WHERE DEPTNO=P_DEPTNO
FOR UPDATE;

BEGIN
    FOR I IN C1(10)
    LOOP
        UPDATE EMPK
        SET SALARY=SALARY
